version: '2.4'

services:
  app:
    image: golang:1.21.6-alpine
    environment:
      - GOPROXY=https://goproxy.cn
      - GO111MODULE=auto
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: tail

  repl:
    # jupyter notebook password
    image: wusuopu/gophernotes:0.7.5
    expose:
      - 8888
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GO111MODULE=auto
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
